### ISSUE TITLE
Connection fails to wss 

### ISSUE THREAD

**Issue by redlock** [deepstreamIO/deepstream.io-client-ios#14]
Hi, When I try to connect to a wss endpoint configured using nginx I get this error from the JRE emulaor:

java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SSLContext TLS implementation not found

am I doing something wrong or is this a bug?

**Comment by oancius** [comment]
Same here! any updates? @akramhussein

**Comment by travisnguyen20** [comment]
Any update? I got the same error
