### ISSUE TITLE
JSON primitive

### ISSUE THREAD

**Issue by jocca1985** [deepstreamIO/deepstream.io-client-ios#6]
When running Example app, getting this after few seconds:
DeepstreamIO_Example[23251:807074] *** Terminating app due to uncaught exception 'JavaLangIllegalStateException', reason: 'java.lang.IllegalStateException: This is not a JSON Primitive.'

**Comment by akramhussein** [comment]
Hi @jocca1985, can you clarify which version of Xcode you are using.
Does Xcode show which line is throwing this error? If possible, can you please provide the stack trace?

**Comment by jocca1985** [comment]
Sorry I am not IOS dev so maybe not the best explanation. Anyway here is some info:

Version 8.2.1
It is in AppDelegate.swift
Line: class AppDelegate: UIResponder, UIApplicationDelegate {

Here is a whole stackTrace: Terminating app due to uncaught exception 'JavaLangIllegalStateException', reason: 'java.lang.IllegalStateException: This is not a JSON Primitive.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107fbed4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107a2021e objc_exception_throw + 48
	2   DeepstreamIO_Example                0x000000010643c87a -[JsonElement getAsJsonPrimitive] + 116
	3   DeepstreamIO_Example                0x00000001063bd10f _TFFFC20DeepstreamIO_Example14ViewController15setupDeepstreamFT_T_U_FT_T_U_FT_T_ + 79
	4   DeepstreamIO_Example                0x00000001063bd4a7 _TTRXFo___XFdCb___ + 39
	5   libdispatch.dylib                   0x000000010a69b978 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000010a6c50cd _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010a6a58a4 _dispatch_main_queue_callback_4CF + 406
	8   CoreFoundation                      0x0000000107f82e49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	9   CoreFoundation                      0x0000000107f4837d __CFRunLoopRun + 2205
	10  CoreFoundation                      0x0000000107f47884 CFRunLoopRunSpecific + 420
	11  GraphicsServices                    0x000000010c636a6f GSEventRunModal + 161
	12  UIKit                               0x00000001084d7c68 UIApplicationMain + 159
	13  DeepstreamIO_Example                0x00000001063c491f main + 111
	14  libdyld.dylib                       0x000000010a71168d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type JavaLangIllegalStateException

**Comment by akramhussein** [comment]
Thanks. How are you testing this? What is running the server and do you have another client running?

**Comment by jocca1985** [comment]
Running the local MacOS server and don't have any other cilents. Maybe you can put some more details in README what else is needed to run this Example and how to test it.

**Comment by akramhussein** [comment]
Hi @jocca1985 

I've tried to recreate this issue but have been unable. To further assist, do you mind gathering a few more pieces of data:

1. Version of swift via the command line:

```$ swift --version```

Example output:
```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

2. Version of deepstream server. Latest is 2.1.2.

3. Xcode path

```xcode-select -p```

Example output:
```
/Applications/Xcode.app/Contents/Developer
```

Regarding the instructions, I will indeed add some. I've raised an issue to do so - #7

**Comment by jocca1985** [comment]
1) and 3) are the same and 2) is 2.1.0

**Comment by akramhussein** [comment]
Ok great, thanks for getting back quickly.

I'll keep investigating and report back.

**Comment by akramhussein** [comment]
There have been significant changes which should address this issue. Please re-open if not so.
