### ISSUE TITLE
Add instructions to README about testing with Example and/or TestApp

### ISSUE THREAD

**Issue by akramhussein** [deepstreamIO/deepstream.io-client-ios#7]
Useful to add instructions on how to test the iOS client using the Example or TestApp.

**Comment by akramhussein** [comment]
Full instructions can be found [here](https://www.deepstreamhub.com/tutorials/getting-started/swift/)

**Comment by mdramos** [comment]
@akramhussein These seem out of date, the build I am using with swift now has different resource files, and `client` has no property `record`

**Comment by akramhussein** [comment]
Hi @mdramos - thanks for raising that, I will update the docs.

I'm not sure why the client doesn't have a record property though, I'll need to take a deeper look.

Which Deepstream iOS library version are you using?

**Comment by mdramos** [comment]
Hey thanks for replying, looks like Im on `2.0.6-c2272`

**Comment by akramhussein** [comment]
Updated README #11.

**Comment by akramhussein** [comment]
@mdramos I've not been able to replicate the issue with `record` property. 

In the extension we have:

```
public extension DeepstreamClient {
    public var record : RecordHandler {
        get {
            return self.getRecordHandler()
        }
    }
...
}
```

Which gives access to it.

To clarify, are you having a compilation issue or is Xcode not auto-completing the usage of this property?

**Comment by akramhussein** [comment]
Just to add, if you take a look at this [line in the example](https://github.com/deepstreamIO/deepstream.io-client-ios/blob/master/Example/DeepstreamIO/ViewController.swift#L56) it uses the `record` property.

**Comment by mdramos** [comment]
@akramhussein ah yea it looks like I was having issues copying over the extensions. All seems to work fine now!

Thanks for the hard work!

**Comment by akramhussein** [comment]
@mdramos no problem.
